import { useState, useRef, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { motion, useScroll, AnimatePresence } from 'framer-motion';
import Loading from '@/components/loading';
import NavigationBar from '@/components/navigationBar';
import HeroSection from '@/components/herosection';
import WavyText from '@/components/wavytext';
import { about } from '@/utils/content';
import HomeCategorySection from '@/components/homeCategorySection';


export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  return (
    <>
      <Head>
        <title>WeDesign Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence>
        {isLoading && (
          <motion.div
            initial={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 5 }}
          >
            <Loading />
          </motion.div>
        )}
      </AnimatePresence>
      <motion.div
        transition={{ duration: 0.25 }}
        className={isLoading ? 'opacity-0' : 'transition-opacity duration-500 opacity-100'}
      >
        <NavigationBar />

        <HeroSection
          isLoading={isLoading}
          setIsLoading={setIsLoading}
        />

        <div className='relative h-[70vh] w-full'>
          <div className='absolute z-0 flex justify-center items-center w-full h-full'>
            <WavyText
              text="ABOUT"
              lowerLetterByPixels={200}
              delay={0}
              duration={0.2}
              childrenTransitionDuration={0.5}
              delayChildrenBy={0.5}
              viewportIntersection={0.4}
              tailwindclasses="text-[250px] text-gray-100 font-semibold font-sans text-center tracking-[0.5em]"
            />
          </div>
          <div className='absolute z-10 bg-transparent flex justify-center items-center w-full h-full'>
            <div className='max-w-4xl'>
              <span>
                <WavyText
                  text="Our projects are one of one"
                  lowerLetterByPixels={100}
                  delay={1}
                  delayChildrenBy={1}
                  duration={0.02}
                  viewportIntersection="all"
                  tailwindclasses='text-3xl text-black font-bold'
                />
              </span>
              <motion.div
                className='overflow-hidden mt-5'
              >
                <motion.p
                  initial={{ opacity: 0, y: 100 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 1, delay: 1 }}
                  viewport={{ once: true, amount: "some" }}
                  className="text-base font-light leading-loose"
                >
                  {about}
                </motion.p>
              </motion.div>
            </div>
          </div>
        </div>

        <HomeCategorySection />
      </motion.div>
    </>
  )
}
